name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test | tee test-results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

  deploy:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Display test results
        run: cat test-results.txt

      - name: Install dependencies
        run: npm install

      
      - name: Install PM2 (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          if (-not (Get-Command pm2 -ErrorAction SilentlyContinue)) {
            npm install -g pm2
          }

     
      - name: Install PM2 (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

     
      - name: Start application with PM2 (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          cd "${{ github.workspace }}" # Ensure correct directory
          if (!(Test-Path server.js)) { Write-Host "ERROR: server.js not found in ${{ github.workspace }}!"; exit 1 }
          pm2 stop node-app; if ($LASTEXITCODE -ne 0) { Write-Host "App not running, proceeding to start it again" }
          pm2 start server.js --name "node-app"

     
      - name: Start application with PM2 (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cd "${{ github.workspace }}" # Ensure correct directory
          if [ ! -f server.js ]; then echo "ERROR: server.js not found in ${{ github.workspace }}!"; exit 1; fi
          pm2 stop node-app || echo "App not running, proceeding to start it again"
          pm2 start server.js --name "node-app"
