name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test | tee test-results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

  deploy:
    needs: test
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Display test results
        run: Get-Content test-results.txt
        shell: pwsh

      - name: Install dependencies
        run: npm install
        shell: pwsh

      - name: Install PM2 (if not installed)
        run: npm install -g pm2
        shell: pwsh

      - name: Start application with PM2
        run: |
          pm2 stop node-app; if ($LASTEXITCODE -ne 0) { Write-Host "Failed to stop node-app, continuing..." }
          pm2 start server.js --name "node-app"
        shell: pwsh
